[package]
name = "l2"
version = "0.3.10"
cairo-version = "2.3.1"
version-The-marquis = "0.0.1"


[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo" }
#starknet = ">=2.2.0"

[[target.dojo]]
build-external-contracts = ["dojo_erc::erc20_contract::*"]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
# Default account for katana with seed = 0
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
